#!/bin/bash

#Author: Vijay Sachdeva
#This script automates the VM migration when we want to empty the resources of specific host and it auto calculates the host with available resources.
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/var/lib/snapd/snap/bin:/root/bin"
echo ""
echo "Fetching Cluster details in cloud"
cls=`cmk list clusters | tr -d '"' | tr -d ',' | tr -d ' ' | egrep -E "^id" | cut -d":" -f2`

for cid in $cls
do
 
	cname=`cmk list clustersmetrics id=$cid | tr -d '"' | tr -d ' ' | egrep -i "^name" | cut -d"," -f1 | cut -d":" -f2`
	memused=`cmk list clustersmetrics id=$cid | tr -d '"' | tr -d ' ' | egrep -i "^memoryused" | cut -d"," -f1 | cut -d":" -f2`
	echo ""
	echo "MemoryUsed on $cname: $memused" 

#####################Capturing all hosts available in the cluster################################################
	echo ""
	chosts=`cmk list hosts clusterid=$cid filter=name,id | egrep -i -e "name" | tr -d '"' | tr -d ' ' | cut -d":" -f2`
	chostsn=`cmk list hosts clusterid=$cid filter=name,id | tr -d ' ' | tr -d '"' | grep -E "^id" | cut -d":" -f2 | cut -d"," -f1`
	for j in  $chostsn
	do 
		percentage=`cmk list hosts id=$j | tr -d '"' | tr -d ' ' | egrep -e "^memoryallocatedpercentage" | cut -d":" -f2 | cut -d"," -f1 | sed -e 's/%//g' | cut -d"." -f1`
		echo "Memory Used on $j:$percentage" >> /opt/cloud-automation/drs/hostspercentage 
		echo "Memory Used on $j:$percentage" 
	done
#####################Calculate Average % of Memory#######################
	totalutilisation=`cat hostspercentage | cut -d":" -f2 | cut -d" " -f2 | xargs | tr \  + | bc`
	totalhosts=`cat hostspercentage | cut -d":" -f2 | cut -d" " -f2 | wc -l`
	totalvalue=$(($totalhosts * 100))
	avgpercentage=`awk "BEGIN {print $totalutilisation/$totalvalue*100}" | cut -d"." -f1`
	echo ""
	echo "Avg Memory Utilisation/Allocation on each host should be: $avgpercentage"
	rm -rf /opt/cloud-automation/drs/hostspercentage

	cmk list hosts clusterid=$cid filter=id | egrep -i -e "id|name" | tr -d '"' | tr -d ' ' | cut -d ":" -f2 > /opt/cloud-automation/drs/allhosts 




################################################################################################################
	echo ""
	echo -e '\033[1;36mChecking Hosts with available resources'
	echo ""
	for host in `cat /opt/cloud-automation/drs/allhosts`
	do
				
		percentage1=`cmk list hosts id=$host | tr -d '"' | tr -d ' ' | egrep -e "^memoryallocatedpercentage" | cut -d":" -f2 | cut -d"," -f1 | sed -e 's/%//g' | cut -d"." -f1`
		if [[ $percentage1 -lt $avgpercentage ]]
		then
			echo "Skipping Host"
		else
			while [[ $percentage1 -gt $avgpercentage  ]]
	
			do	
				cat /opt/cloud-automation/drs/allhosts | grep -v $host > /opt/cloud-automation/drs/hosts
				for resavail in `cat /opt/cloud-automation/drs/hosts`
				do
					percentage2=`cmk list hosts id=$resavail | tr -d '"' | tr -d ' ' | egrep -e "^memoryallocatedpercentage" | cut -d":" -f2 | cut -d"," -f1 | sed -e 's/%//g' | cut -d"." -f1`
					if [[ $percentage2 -lt $avgpercentage ]]
					then
						echo "$resavail" >> /opt/cloud-automation/drs/available-resources
					fi
				done
				if [[ `cat /opt/cloud-automation/drs/available-resources` == "" ]]
				then
					exit 0
				else
		
					newres=`cat /opt/cloud-automation/drs/available-resources | tail -n 1`
					cmk list virtualmachines hostid=$host listall=true filter=id | tr -d '"' | tr -d ' ' | egrep "^id" | cut -d":" -f2 > /opt/cloud-automation/drs/vmlist

					cmk list routers listall=true hostid=$host listall=true filter=id,name,state | egrep -i -e "id|running"  | tr -d '"' | tr -d ' ' | cut -d ":" -f2 | cut -d "," -f1 | grep -v "Running" > /opt/cloud-automation/drs/vrlist

					cat /opt/cloud-automation/drs/vmlist /opt/cloud-automation/drs/vrlist > /opt/cloud-automation/drs/allvms 

					vm=`cat /opt/cloud-automation/drs/allvms | tail -n 1`
					if [[ `cmk list routers id=$vm  | tr -d '"' | tr -d ',' | tr -d ' ' | egrep "^role" | cut -d":" -f2` == "VIRTUAL_ROUTER" ]]
					then
						echo "Migrating Virtual-Router $vm on host $newres"
						cmk migrate systemvm virtualmachineid=$vm hostid=$newres
					else
						echo "Migrating Virtual Machine $vm on host $newres"
					        cmk migrate virtualmachine virtualmachineid=$vm hostid=$newres
					fi
				fi
			
				sleep 5
				percentage1=`cmk list hosts id=$host | tr -d '"' | tr -d ' ' | egrep -e "^memoryallocatedpercentage" | cut -d":" -f2 | cut -d"," -f1 | sed -e 's/%//g' | cut -d"." -f1`
				cat /dev/null > /opt/cloud-automation/drs/available-resources

			done
		fi
	done
done

echo ""
echo -e '\033[1;32mDRS completed successfully :)'
##################################################################################################################
